import{a as R,S as q,i as s}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function u(e){if(e.ep)return;e.ep=!0;const i=r(e);fetch(e.href,i)}})();async function p(t,o){try{return(await R.get("https://pixabay.com/api/",{params:{key:"51711759-c98880f89c2a2cc3e02319f38",q:t.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}catch(r){throw console.error("Помилка при отриманні зображень:",r),r}}const g=document.querySelector(".gallery"),n=document.querySelector(".box-loader"),a=document.querySelector("#load-more"),E=new q(".gallery-item a",{captionsData:"alt",captionDelay:250});function m(t){const o=t.map(({webformatURL:r,largeImageURL:u,tags:e,likes:i,views:l,comments:v,downloads:S})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${u}">
    <img class="gallery-image" src="${r}" alt="${e}" loading="lazy"/>
  </a>

  <ul class="list-description">
    <li class="item-description"><strong>Likes</strong><p>${i}</p></li>
    <li class="item-description"><strong>Views</strong><p>${l}</p></li>
    <li class="item-description"><strong>Comments</strong><p>${v}</p></li>
    <li class="item-description"><strong>Downloads</strong><p>${S}</p></li>
  </ul>
</li>`).join("");g.insertAdjacentHTML("beforeend",o),E.refresh()}function P(){g.innerHTML=""}function y(){n==null||n.classList.remove("is-hidden")}function L(){n==null||n.classList.add("is-hidden")}function x(){a==null||a.classList.remove("is-hidden")}function f(){a==null||a.classList.add("is-hidden")}function H(){const t=g.firstElementChild;return t?t.getBoundingClientRect().height:0}const w=document.querySelector(".form"),O=document.querySelector("#load-more");let d="",c=1;const b=15;let h=0;w.addEventListener("submit",C);O.addEventListener("click",$);async function C(t){t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){s.error({title:"Please write a word!",position:"topRight"});return}d=o,c=1,h=0,P(),f();try{y();const r=await p(d,c);if(!r.hits||r.hits.length===0){s.error({title:`Sorry, there are no images matching your search "${d}". Please try again!`,position:"topRight"});return}h=r.totalHits??r.hits.length,m(r.hits),c*b<h?x():(f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){s.error({title:"Error",message:r.message,position:"topRight"})}finally{L(),w.reset()}}async function $(){try{c+=1,y();const t=await p(d,c);if(!t.hits||t.hits.length===0){f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}const o=H();m(t.hits),c*b>=h&&(f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),o&&window.scrollBy({top:o*2,behavior:"smooth"})}catch(t){s.error({title:"Error",message:t.message,position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
